on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]


# # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
# permissions:
#   contents: read
#   pages: write
#   id-token: write

jobs:
  build_project:
    runs-on: ubuntu-latest
    name: Build project
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Checkout project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install elan
        run: curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y --default-toolchain leanprover/lean4:4.0.0

      # Lean4Hacking.lean should import all the files.
      - name: update Lean4Hacking.lean
        run: |
          find Lean4Hacking -name "*.lean" | LC_ALL=C sort | sed 's/\.lean//;s,/,.,g;s/^/import /' > Lean4Hacking.lean

      - name: Get cache
        run: ~/.elan/bin/lake -Kenv=dev exe cache get

      - name: Build project
        run: ~/.elan/bin/lake -Kenv=dev build Lean4Hacking

      - name: check that all files are imported
        run: git diff --exit-code

      - name: check environments using lean4checker
        id: lean4checker
        run: |
          git clone https://github.com/leanprover/lean4checker
          cd lean4checker
          git checkout toolchain/v4.5.0-rc1
          # Now that the git hash is embedded in each olean,
          # we need to compile lean4checker on the same toolchain
          cp ../lean-toolchain .
          ~/.elan/bin/lake build
          # sed -i 's/lake/~\/.elan\/bin\/lake/g' ./test.sh
          # ./test.sh
          cd ..

          # Remove proofwidgets because it uses oleans built on another system, which lean4checker rejects
          rm -rf .lake/packages/proofwidgets/.lake/build/lib
          rm -rf .lake/packages/proofwidgets/.lake/build/ir

          xxd ./.lake/build/lib/Mathlib.olean | head -5 
          xxd ./lean4checker/.lake/build/lib/Lean4Checker.olean | head -5

          ~/.elan/bin/lake env lean4checker/.lake/build/bin/lean4checker
